package models.enumerate;

public enum ShiftTroubles {

  FUTURE_DAY,
  PERSON_NOT_ASSIGNED,
  NOT_COMPLETE_SHIFT,
  OUT_OF_STAMPING_TOLERANCE,
  NOT_ENOUGH_WORKING_TIME,
  PROBLEMS_ON_OTHER_SLOT,
  PERSON_IS_ABSENT,
  EXCEEDED_BREAKTIME
}
