FROM play1:1.4.2-jdk-alpine as builder

ENV APP_HOME /epas

RUN apk --no-cache add apache-ant

ADD / $APP_HOME
WORKDIR $APP_HOME

RUN touch conf/dev.conf && \
    play clean && \
    play deps --sync --forProd && \
    ant build -Dplay.path=$PLAY_PATH && \
    play precompile && \
    mkdir attachments logs tools backups

FROM play1:1.4.2-jre-alpine

ENV APP_HOME /home/epas/epas
ENV user epas
ENV APP ePas

RUN  addgroup -g 1001 -S $user && \
     adduser -u 1001 -G $user -S -H -h /home/epas -s /sbin/nologin $user

USER $user
WORKDIR $APP_HOME

COPY --chown=epas --from=builder /epas $APP_HOME

VOLUME ["/home/epas/epas/logs", "/home/epas/epas/data/attachments", "/home/epas/epas/backups"]

ENTRYPOINT ["/home/epas/epas/docker_conf/init"]

CMD ["app:run"]
