package models.flows.enumerate;

public enum CompetenceRequestEventType {

  STARTING_APPROVAL_FLOW,
  EMPLOYEE_APPROVAL,
  EMPLOYEE_REFUSAL,
  MANAGER_APPROVAL,
  MANAGER_REFUSAL,
  ADMINISTRATIVE_APPROVAL,
  ADMINISTRATIVE_REFUSAL,
  OFFICE_HEAD_APPROVAL,
  OFFICE_HEAD_REFUSAL,
  COMPLETE,
  EPAS_REFUSAL,
  DELETE,
  EXPIRING;
}
