package models.flows.enumerate;

public enum InformationRequestEventType {

  STARTING_APPROVAL_FLOW,
  OFFICE_HEAD_ACKNOWLEDGMENT,
  OFFICE_HEAD_REFUSAL,
  ADMINISTRATIVE_ACKNOWLEDGMENT,
  ADMINISTRATIVE_REFUSAL,
  DELETE,
  EPAS_REFUSAL,
  COMPLETE;
}
