package manager.services.telework.errors;

public enum TeleworkStampingError {
  MEAL_STAMPING_PRESENT,
  MEAL_STAMPING_OUT_OF_BOUNDS,
  BEGIN_STAMPING_PRESENT,
  BEGIN_STAMPING_AFTER_END,
  END_STAMPING_PRESENT,
  END_STAMPING_BEFORE_BEGIN,
  INTERRUPTION_OUT_OF_BOUNDS,
  INTERRUPTION_IN_MEAL_TIME,
  EXISTING_STAMPING_BEFORE_BEGIN,
  EXISTING_STAMPING_AFTER_END,
  EXISTING_BEGIN_STAMPING_AFTER_END_MEAL,
  EXISTING_END_STAMPING_BEFORE_BEGIN_MEAL;
}
