package models.absences.definitions;

import com.google.common.base.Optional;
import com.google.common.collect.ImmutableSet;
import com.google.common.collect.Lists;

import java.util.List;
import java.util.Set;

import models.absences.AbsenceType;
import models.absences.JustifiedType.JustifiedTypeName;

import org.joda.time.LocalDate;

/**
 * Tipi assenza di default.
 * 
 * @author alessandro
 *
 */
public enum DefaultAbsenceType {

  A_18M("18M", "Permesso assistenza parenti/affini disabili L. 104/92 in ore e minuti",
      true, ImmutableSet.of(JustifiedTypeName.specified_minutes), 0, false, false,
      0, null, null, null),
  A_18("18", "Permesso assistenza parenti/affini disabili L. 104/92 intera giornata",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_18H1("18H1", "Permesso assistenza parenti/affini disabili L. 104/92 completamento 1 ora",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      60, JustifiedTypeName.absence_type_minutes, null, null),
  A_18H2("18H2", "Permesso assistenza parenti/affini disabili L. 104/92 completamento 2 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      120, JustifiedTypeName.absence_type_minutes, null, null),
  A_18H3("18H3", "Permesso assistenza parenti/affini disabili L. 104/92 completamento 3 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      180, JustifiedTypeName.absence_type_minutes, null, null),
  A_18H4("18H4", "Permesso assistenza parenti/affini disabili L. 104/92 completamento 4 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      240, JustifiedTypeName.absence_type_minutes, null, null),
  A_18H5("18H5", "Permesso assistenza parenti/affini disabili L. 104/92 completamento 5 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      300, JustifiedTypeName.absence_type_minutes, null, null),
  A_18H6("18H6", "Permesso assistenza parenti/affini disabili L. 104/92 completamento 6 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      360, JustifiedTypeName.absence_type_minutes, null, null),
  A_18H7("18H7", "Permesso assistenza parenti/affini disabili L. 104/92 completamento 7 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      420, JustifiedTypeName.absence_type_minutes, null, null),
  A_18H8("18H8", "Permesso assistenza parenti/affini disabili L. 104/92 completamento 8 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      480, JustifiedTypeName.absence_type_minutes, null, null),
  A_18H9("18H9", "Permesso assistenza parenti/affini disabili L. 104/92 completamento 9 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      540, JustifiedTypeName.absence_type_minutes, null, null),
  A_18P("18P", "Permesso provvisorio assistenza parenti/affini disabili L. 104/92 intera giornata",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  
  A_182M("182M", "Permesso assistenza secondo parenti/affini disabili L. 104/92 in ore e minuti",
      true, ImmutableSet.of(JustifiedTypeName.specified_minutes), 0, false, false,
      0, null, null, null),
  A_182("182", "Permesso assistenza secondo parenti/affini disabili L. 104/92 intera giornata",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_182H1("182H1", "Permesso assistenza secondo parenti/affini disabili L.104/92 compl. 1 ora",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      60, JustifiedTypeName.absence_type_minutes, null, null),
  A_182H2("182H2", "Permesso assistenza secondo parenti/affini disabili L.104/92 compl. 2 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      120, JustifiedTypeName.absence_type_minutes, null, null),
  A_182H3("182H3", "Permesso assistenza secondo parenti/affini disabili L.104/92 compl. 3 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      180, JustifiedTypeName.absence_type_minutes, null, null),
  A_182H4("182H4", "Permesso assistenza secondo parenti/affini disabili L.104/92 compl. 4 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      240, JustifiedTypeName.absence_type_minutes, null, null),
  A_182H5("182H5", "Permesso assistenza secondo parenti/affini disabili L.104/92 compl. 5 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      300, JustifiedTypeName.absence_type_minutes, null, null),
  A_182H6("182H6", "Permesso assistenza secondo parenti/affini disabili L.104/92 compl. 6 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      360, JustifiedTypeName.absence_type_minutes, null, null),
  A_182H7("182H7", "Permesso assistenza secondo parenti/affini disabili L.104/92 compl. 7 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      420, JustifiedTypeName.absence_type_minutes, null, null),
  A_182H8("182H8", "Permesso assistenza secondo parenti/affini disabili L.104/92 compl. 8 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      480, JustifiedTypeName.absence_type_minutes, null, null),
  A_182H9("182H9", "Permesso assistenza secondo parenti/affini disabili L.104/92 compl. 9 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      540, JustifiedTypeName.absence_type_minutes, null, null),
  A_182P("182P", "Permesso provvisorio assistenza secondo parenti/affini disabili L. 104/92 intera giornata",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),

  A_19M("19M", "Permesso per dipendente disabile L. 104/92 in ore e minuti",
      true, ImmutableSet.of(JustifiedTypeName.specified_minutes), 0, false, false,
      0, null, null, null),
  A_19("19", "Permesso per dipendente disabile L. 104/92 intera giornata",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_19H1("19H1", "Permesso per dipendente disabile L. 104/92 completamento 1 ora",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      60, JustifiedTypeName.absence_type_minutes, null, null),
  A_19H2("19H2", "Permesso per dipendente disabile L. 104/92 completamento 2 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      120, JustifiedTypeName.absence_type_minutes, null, null),
  A_19H3("19H3", "Permesso per dipendente disabile L. 104/92 completamento 3 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      180, JustifiedTypeName.absence_type_minutes, null, null),
  A_19H4("19H4", "Permesso per dipendente disabile L. 104/92 completamento 4 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      240, JustifiedTypeName.absence_type_minutes, null, null),
  A_19H5("19H5", "Permesso per dipendente disabile L. 104/92 completamento 5 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      300, JustifiedTypeName.absence_type_minutes, null, null),
  A_19H6("19H6", "Permesso per dipendente disabile L. 104/92 completamento 6 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      360, JustifiedTypeName.absence_type_minutes, null, null),
  A_19H7("19H7", "Permesso per dipendente disabile L. 104/92 completamento 7 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      420, JustifiedTypeName.absence_type_minutes, null, null),
  A_19H8("19H8", "Permesso per dipendente disabile L. 104/92 completamento 8 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      480, JustifiedTypeName.absence_type_minutes, null, null),
  A_19H9("19H9", "Permesso per dipendente disabile L. 104/92 completamento 9 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      540, JustifiedTypeName.absence_type_minutes, null, null),
  A_19P("19P", "Permesso provvisorio per dipendente disabile L. 104/92 intera giornata",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  
  //Il tempo per buono pasto in questo momento è disabilitato. Capire.
  A_26("26", "Permesso per dipendente disabile L. 104/92 due ore giornaliere",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  
  A_C17("C17", "Congedo assistenza figlio disabile L. 104/92",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_C18("C18", "Congedo straordinario per assistenza L. 104/92",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  
  A_661M("661M", "Permesso orario per motivi personali in ore e minuti",
      true, ImmutableSet.of(JustifiedTypeName.specified_minutes), 0, false, false,
      0, null, null, null),
  A_661H1("661H1", "Permesso orario per motivi personali completamento 1 ora",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      60, JustifiedTypeName.absence_type_minutes, null, null),
  A_661H2("661H2", "Permesso orario per motivi personali completamento 2 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      120, JustifiedTypeName.absence_type_minutes, null, null),
  A_661H3("661H3", "Permesso orario per motivi personali completamento 3 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      180, JustifiedTypeName.absence_type_minutes, null, null),
  A_661H4("661H4", "Permesso orario per motivi personali completamento 4 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      240, JustifiedTypeName.absence_type_minutes, null, null),
  A_661H5("661H5", "Permesso orario per motivi personali completamento 5 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      300, JustifiedTypeName.absence_type_minutes, null, null),
  A_661H6("661H6", "Permesso orario per motivi personali completamento 6 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      360, JustifiedTypeName.absence_type_minutes, null, null),
  A_661H7("661H7", "Permesso orario per motivi personali completamento 7 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      420, JustifiedTypeName.absence_type_minutes, null, null),
  A_661H8("661H8", "Permesso orario per motivi personali completamento 8 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      480, JustifiedTypeName.absence_type_minutes, null, null),
  A_661H9("661H9", "Permesso orario per motivi personali completamento 9 ore",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      540, JustifiedTypeName.absence_type_minutes, null, null),

  A_89("89", "Permesso diritto allo studio completamento giornata",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      0, JustifiedTypeName.all_day, null, null),
  A_89M("89M", "Permesso diritto allo studio in ore e minuti",
      true, ImmutableSet.of(JustifiedTypeName.specified_minutes), 0, false, false,
      0, null, null, null),
  A_99("99", "permesso per diritto allo studio",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  
  A_09B("09B", "Permesso visita medica completamento giornata",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      0, JustifiedTypeName.all_day, null, null),
  A_09M("09M", "Permesso visita medica in ore e minuti",
      true, ImmutableSet.of(JustifiedTypeName.specified_minutes), 0, false, false,
      0, null, null, null),
  A_09BI("09B", "Permesso visita medica completamento giornata da importazione",
      true, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      0, null, null, null),
  
  A_631("631", "Permesso visita medica",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),

  A_92("92", "Missione",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  A_92H1("92H1", "Missione 1 ora",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, true, true,
      0, null, null, null),
  A_92H2("92H2", "Missione 2 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, true, true,
      0, null, null, null),
  A_92H3("92H3", "Missione 3 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, true, true,
      0, null, null, null),
  A_92H4("92H4", "Missione 4 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, true, true,
      0, null, null, null),
  A_92H5("92H5", "Missione 5 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, true, true,
      0, null, null, null),
  A_92H6("92H6", "Missione 6 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, true, true,
      0, null, null, null),
  A_92H7("92H7", "Missione 7 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, true, true,
      0, null, null, null),


  A_31("31", "Ferie anno precedente",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_94("94", "festività soppresse (ex legge 937/77)",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_32("32", "Ferie anno corrente",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_37("37", "ferie anno precedente (dopo il 31/8)",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),

  A_91("91", "Riposo compensativo",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_91MS("91", "Riposo compensativo missione sabato",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_91MD("91", "Riposo compensativo missione domenica",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),


  A_PB("PB", "Permesso breve 36 ore anno",
      true, ImmutableSet.of(JustifiedTypeName.specified_minutes_limit), 0, false, false,
      0, null, null, null),

  A_105BP("105BP", "Lavoro Fuori Sede - Intera Giornata",
      false, ImmutableSet.of(JustifiedTypeName.assign_all_day), 0, false, false,
      0, null, null, null),
  
  A_23("23", "Astensione facoltativa post partum 100% primo figlio intera giornata",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  A_23M("23M", "Astensione facoltativa post partum 100% primo figlio in ore e minuti",
      true, ImmutableSet.of(JustifiedTypeName.specified_minutes), 0, false, false,
      0, null, null, null),
  A_23H7("23H7", "Astensione facoltativa post partum 100% primo figlio completamento giornata",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      0, JustifiedTypeName.all_day, null, null),
  A_23U("23U", "Astensione facoltativa post partum 100% primo figlio intera giornata altro genitore",
      true, ImmutableSet.of(JustifiedTypeName.all_day_limit), 0, true, false,
      0, null, null, null),

  A_25("25", "Astensione facoltativa post partum 30% primo figlio intera giornata",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  A_25M("25M", "Astensione facoltativa post partum 30% primo figlio in ore e minuti",
      true, ImmutableSet.of(JustifiedTypeName.specified_minutes), 0, false, false,
      0, null, null, null),
  A_25H7("25H7", "Astensione facoltativa post partum 30% primo figlio completamento giornata",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      0, JustifiedTypeName.all_day, null, null),
  A_25U("25U", "Astensione facoltativa post partum 30% primo figlio intera giornata altro genitore",
      true, ImmutableSet.of(JustifiedTypeName.all_day_limit), 0, true, false,
      0, null, null, null),

  A_24("24", "Astensione facoltativa post partum non retrib. primo figlio intera giornata",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_24M("24M", "Astensione facoltativa post partum non retrib. primo figlio in ore e minuti",
      true, ImmutableSet.of(JustifiedTypeName.specified_minutes), 0, false, false,
      0, null, null, null),
  A_24H7("24H7", "Astensione facoltativa post partum non retrib. primo figlio completamento giornata",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      0, JustifiedTypeName.all_day, null, null),
  A_24U("24U", "Astensione facoltativa post partum non retrib. primo figlio intera giornata altro genitore",
      true, ImmutableSet.of(JustifiedTypeName.all_day_limit), 0, false, false,
      0, null, null, null),

  A_232("232", "Astensione facoltativa post partum 100% secondo figlio intera giornata",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  A_232M("232M", "Astensione facoltativa post partum 100% secondo figlio in ore e minuti",
      true, ImmutableSet.of(JustifiedTypeName.specified_minutes), 0, false, false,
      0, null, null, null),
  A_232H7("232H7", "Astensione facoltativa post partum 100% secondo figlio completamento giornata",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      0, JustifiedTypeName.all_day, null, null),
  A_232U("232U", "Astensione facoltativa post partum 100% secondo figlio intera giornata altro genitore",
      true, ImmutableSet.of(JustifiedTypeName.all_day_limit), 0, true, false,
      0, null, null, null),
  
  A_252M("252M", "Astensione facoltativa post partum 30% secondo figlio in ore e minuti",
      true, ImmutableSet.of(JustifiedTypeName.specified_minutes), 0, false, false,
      0, null, null, null),
  A_252("252", "Astensione facoltativa post partum 30% secondo figlio intera giornata",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  A_252H7("252H7", "Astensione facoltativa post partum 30% secondo figlio completamento giornata",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      0, JustifiedTypeName.all_day, null, null),
  A_252U("252U", "Astensione facoltativa post partum 30% secondo figlio intera giornata altro genitore",
      true, ImmutableSet.of(JustifiedTypeName.all_day_limit), 0, true, false,
      0, null, null, null),

  A_242("242", "Astensione facoltativa post partum non retrib. secondo figlio intera giornata",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_242M("242M", "Astensione facoltativa post partum non retrib. secondo figlio in ore e minuti",
      true, ImmutableSet.of(JustifiedTypeName.specified_minutes), 0, false, false,
      0, null, null, null),
  A_242H7("242H7", "Astensione facoltativa post partum non retrib. secondo figlio completamento giornata",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      0, JustifiedTypeName.all_day, null, null),
  A_242U("242U", "Astensione facoltativa post partum non retrib. secondo figlio intera giornata altro genitore",
      true, ImmutableSet.of(JustifiedTypeName.all_day_limit), 0, false, false,
      0, null, null, null),

  A_233("233", "Astensione facoltativa post partum 100% terzo figlio intera giornata",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  A_233M("233M", "Astensione facoltativa post partum 100% terzo figlio in ore e minuti",
      true, ImmutableSet.of(JustifiedTypeName.specified_minutes), 0, false, false,
      0, null, null, null),
  A_233H7("233H7", "Astensione facoltativa post partum 100% terzo figlio completamento giornata",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      0, JustifiedTypeName.all_day, null, null),
  A_233U("233U", "Astensione facoltativa post partum 100% terzo figlio intera giornata altro genitore",
      true, ImmutableSet.of(JustifiedTypeName.all_day_limit), 0, true, false,
      0, null, null, null),

  A_253("253", "Astensione facoltativa post partum 30% terzo figlio intera giornata",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  A_253M("253M", "Astensione facoltativa post partum 30% terzo figlio in ore e minuti",
      true, ImmutableSet.of(JustifiedTypeName.specified_minutes), 0, false, false,
      0, null, null, null),
  A_253H7("253H7", "Astensione facoltativa post partum 30% terzo figlio completamento giornata",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      0, JustifiedTypeName.all_day, null, null),
  A_253U("253U", "Astensione facoltativa post partum 30% terzo figlio intera giornata altro genitore",
      true, ImmutableSet.of(JustifiedTypeName.all_day_limit), 0, true, false,
      0, null, null, null),

  A_243("243", "Astensione facoltativa post partum non retrib. terzo figlio intera giornata",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),

  A_243M("243M", "Astensione facoltativa post partum non retrib. terzo figlio in ore e minuti",
      true, ImmutableSet.of(JustifiedTypeName.specified_minutes), 0, false, false,
      0, null, null, null),
  A_243H7("243H7", "Astensione facoltativa post partum non retrib. terzo figlio completamento giornata",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      0, JustifiedTypeName.all_day, null, null),
  A_243U("243U", "Astensione facoltativa post partum non retrib. terzo figlio intera giornata altro genitore",
      true, ImmutableSet.of(JustifiedTypeName.all_day_limit), 0, false, false,
      0, null, null, null),
      
  A_25P("25P", "Prolungamento astensione facoltativa post partum 30% intera giornata",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  A_25PM("25M", "Prolungamento astensione facoltativa post partum 30% in ore e minuti",
      true, ImmutableSet.of(JustifiedTypeName.specified_minutes), 0, false, false,
      0, null, null, null),
  A_25PH7("25H7", "Prolungamento astensione facoltativa post partum 30% completamento giornata",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      0, JustifiedTypeName.all_day, null, null),
  
  A_20("20", "Congedo/permesso DPR 1026 Art. 20",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  
  A_21("21", "Congedo/permesso per maternità",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  
  A_111("111", "Malattia",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  A_11S("11S", "Malattia superiore a 15 gg lav.",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  A_115("115", "Malattia superiore a 12 mesi",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  A_116("116", "Malattia superiore a 18 mesi",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  A_117("117", "Terapia invalidante grave patologia",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  A_118("118", "Malattia con responsabilita' di terzi",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  A_119("119", "Malattia superiore a nove mesi",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  A_11R("11R", "Malattia con ricovero",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  A_11R5("11R5", "Ricovero dopo malattia superiore a 12 mesi",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  A_11R9("11R9", "Ricovero dopo malattia superiore a 9 mesi",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  A_11C("11C", "Malattia post-ricovero",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  A_11C5("11C5", "Convalescenza dopo malattia superiore a 12 mesi",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  A_11C9("11C9", "Convalescenza dopo malattia superiore a 9 mesi",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),

  
  A_12("12", "malattia primo figlio/a <= 3 anni retribuita 100%",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),

  A_13("13", "malattia primo figlio/a > 3 anni senza retr.",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),

  A_14("14", "malattia primo figlio non retribuita",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),

  A_122("122", "malattia secondo figlio/a <= 3 anni retribuita 100%",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  
  A_132("132", "malattia secondo figlio/a > 3 anni senza retr.",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),

  A_142("142", "malattia secondo figlio non retribuita",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, new LocalDate(1990, 1, 1), new LocalDate(2008, 12, 31)),
  
  A_123("123", "malattia terzo figlio/a <= 3 anni retribuita 100%",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),

  A_133("133", "malattia terzo figlio/a > 3 anni senza retr.",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),

  A_143("143", "malattia terzo figlio non retribuita",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, new LocalDate(1990, 1, 1), new LocalDate(2008, 12, 31)),
  
  //Altri codici

  A_45("45", "Congedo straordinario permesso per matrimonio",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  
  A_103("103", "Telelavoro",
      false, ImmutableSet.of(JustifiedTypeName.assign_all_day), 0, true, false,
      0, null, null, null),
  A_103BP("103BP", "Telelavoro buono pasto",
      false, ImmutableSet.of(JustifiedTypeName.assign_all_day), 0, true, true,
      0, null, null, null),
  
  A_71("71", "permesso sindacale 1 ora",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_72("72", "permesso sindacale 2 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  A_73("73", "permesso sindacale 3 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_74("74", "permesso sindacale 4 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_75("75", "permesso sindacale 5 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, true,
      0, null, null, null),
  A_76("76", "permesso sindacale 6 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_77("77", "permesso sindacale 7 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  A_78("78", "permesso sindacale 8 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 480, false, false,
      0, null, null, null),
  
  A_71A("71A", "permesso sindacale 1 ora non retribuita",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_72A("72A", "permesso sindacale 2 ore non retribuita",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  A_73A("73A", "permesso sindacale 3 ore non retribuita",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_74A("74A", "permesso sindacale 4 ore non retribuita",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_75A("75A", "permesso sindacale 5 ore non retribuita",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_76A("76A", "permesso sindacale 6 ore non retribuita",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_77A("77A", "permesso sindacale 7 ore non retribuito",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  A_78A("78A", "permesso sindacale 8 ore non retribuita",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 480, false, false,
      0, null, null, null),
  
  A_71S("71S", "perm.1 ora rapp.lavoratori",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_72S("72S", "perm.2 ore rapp.lavoratori",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  A_73S("73S", "perm.3 ore rapp.lavoratori",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_74S("74S", "perm.4 ore rapp.lavoratori",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_75S("75S", "perm.5 ore rapp.lavoratori",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_76S("76S", "perm.6 ore rapp.lavoratori",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_77S("77S", "perm.7 ore rapp.lavoratori",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  
  A_71R("71R", "perm. sind. 1 ora R.S.U.",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_72R("72R", "perm. sind. 2 ore R.S.U.",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  A_73R("73R", "perm. sind. 3 ore R.S.U",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_74R("74R", "perm. sind. 4 ore R.S.U.",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_75R("75R", "perm. sind. 5 ore R.S.U.",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_76R("76R", "perm. sind. 6 ore R.S.U.",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_77R("77R", "perm. sind. 7 ore R.S.U.",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  
  A_71D("71D", "perm. sind. 1 ora dirigenti sidac.",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_72D("72D", "perm. sind. 2 ore dirigenti sindac.",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  A_73D("73D", "perm. sind. 3 ore dirigenti sindac.",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_74D("74D", "perm. sind. 4 ore dirigenti sindac.",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_75D("75D", "perm. sind. 5 ore dirigenti sindac.",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_76D("76D", "perm. sind. 6 ore dirigenti sindac.",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_77D("77D", "perm. sind. 7 ore dirigenti sindac.",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  A_78D("78D", "perm. sind. 8 ore dirigenti sindac.",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 480, false, false,
      0, null, null, null),
  
  A_01("01", "assemblea 1 ora",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_02("02", "assemblea 2 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  A_03("03", "assemblea 3 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_04("04", "assemblea 4 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_05("05", "assemblea 5 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_06("06", "assemblea 6 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_07("07", "assemblea 7 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  A_08("08", "assemblea 8 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 480, false, false,
      0, null, null, null),
  
  A_FA1("FA1", "formazione e aggiornamento 1 ora",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_FA2("FA2", "formazione e aggiornamento 2 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  A_FA3("FA3", "formazione e aggiornamento 3 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_FA4("FA4", "formazione e aggiornamento 4 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_FA5("FA5", "formazione e aggiornamento 5 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_FA6("FA6", "formazione e aggiornamento 6 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_FA7("FA7", "formazione e aggiornamento 7 ore",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  
  A_OA1("OA1", "ore aggiuntive 1",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      0, null, null, null),
  A_OA2("OA2", "ore aggiuntive 2",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      0, null, null, null),
  A_OA3("OA3", "ore aggiuntive 3",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      0, null, null, null),
  A_OA4("OA4", "ore aggiuntive 4",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      0, null, null, null),
  A_OA5("OA5", "ore aggiuntive 5",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      0, null, null, null),
  A_OA6("OA6", "ore aggiuntive 6",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      0, null, null, null),
  A_OA7("OA7", "ore aggiuntive 7",
      false, ImmutableSet.of(JustifiedTypeName.nothing), 0, false, false,
      0, null, null, null),
  
  A_16("16", "congedo straordinario per volontariato",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_33("33", "congedo per motivi di studio retribuito",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_33B("33B", "congedo per motivi di studio retribuito / borsa CNR",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_33C("33C", "congedo per motivi di studio retribuito / cooperaz.",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_34("34", "congedo per motivi di studio non retribuito",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_38("38", "infortunio in itinere o causa servizio da riconoscere",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
      0, null, null, null),
  A_39("39", "aspettativa infortunio in itinere riconosciuto",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_681("681", "permesso lutto di famiglia",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_691("691", "permesso secondo lutto di famiglia",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_441("441", "permesso esami",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_6N("6N", "permesso motivi privati non retribuito",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_67("67", "permesso donazione sangue",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_80("80", "sciopero intera giornata",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_662("662", "permesso grave inferm. coniuge o parente",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
   A_62S50V("62S50V", "dist. sind.a temp. det. p. t. 50% vert.",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
   A_79("79", "concorso interno",
       false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
       0, null, null, null),
   A_ES_L133("ES-L133", "esonero servizio art.72 L.133/08",
       false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true, false,
       0, null, null, null),
   A_65("65", "causa forza maggiore da recuperare",
       false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
       0, null, null, null),
   A_61("61", "causa forza maggiore recuperato",
       false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
       0, null, null, null),
   A_42("42", "permesso cure invalidita' per servizio",
       false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
       0, null, null, null),
   A_93("93", "incarico di insegnamento",
       false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
       0, null, null, null),
  
  A_54("54", "aspett. per mot. di famigl.o studio",               
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true /*festivo capire*/, false,    
      0, null, null, null),
  A_54C("54C", "aspett. per cooperaz. Paesi in sviluppo",               
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true /*festivo capire*/, false,    
      0, null, null, null),
  A_54D("54D", "aspett.per nomina a Dirett.Ammin.",               
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true /*festivo capire*/, false,    
      0, null, null, null),
  A_54E("54E", "congedo eventi cause particolari",               
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true /*festivo capire*/, false,    
      0, null, null, null),
  A_54F("54F", "aspett. motivi fam. progetto recupero",               
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true /*festivo capire*/, false,    
      0, null, null, null),
  A_54P("54P", "aspett. per periodo di prova",               
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true /*festivo capire*/, false,    
      0, null, null, null),
  A_54A17("54A17", "aspett. art17 CL0609 max 12 mesi",               
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true /*festivo capire*/, false,    
      0, null, null, null),
  A_54CNR("54CNR", "aspett. per incarico CNR (Direzione)",               
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true /*festivo capire*/, false,    
      0, null, null, null),
  A_54ORGPP("54ORGPP", "asp.s/ass. ex art. 23bis DLgs165/2001",               
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true /*festivo capire*/, false,    
      0, null, null, null),
  A_54L230("54L230", "asp.s/ass. contrat.priv. L.230/2005",               
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true /*festivo capire*/, false,    
      0, null, null, null),
  A_54R("54R", "aspett. motivi fam. progetto recupero",               
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true /*festivo capire*/, false,    
      0, null, null, null),
  A_54VV("54VV", "congedo per donne vittime di violenza",               
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true /*festivo capire*/, false,    
      0, null, null, null),
  A_54VVH7("54VVH7", "comp. congedo donne vittime di violenza",               
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, true /*festivo capire*/, false,    
      0, null, null, null),
  
  A_95046("95046", "perm. funz. pubb. giunte provin. 6 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_95053("95053", "perm. funz. pubb. comun. Giunt. Comm. 3 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_95053E("95053E", "perm. funz. pubb. O. E. com. e Un. com. 3 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_95053P("95053P", "perm. funz. pubb. Pres. Cons. comun. 3 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_95054("95054", "perm. funz. pubb. comun. Giunt. Comm. 4 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_95054E("95054E", "perm. funz. pubb. O. E. com. e Un. com. 4 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_95054P("95054P", "perm. funz. pubb. Pres. Cons. comun. 4 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_95055("95055", "perm. funz. pubb. comun. Giunt. Comm. 5 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_95055E("95055E", "perm. funz. pubb. O. E. com. e Un. com. 5 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_95055P("95055P", "perm. funz. pubb. Pres. Cons. comun. 5 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_95056("95056", "perm. funz. pubb. comun. Giunt. Comm. 6 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_95052P("95052P", "perm. funz. pubb. Pres. Cons. comun. 2 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  A_95052E("95052E", "perm. funz. pubb. O. E. com. e Un. com. 2 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  A_95052("95052", "perm. funz. pubb. comun. Giunt. Comm. 2 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  A_95046E("95046E", "perm. funz. pubb. O. E. provinciali 6 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_95046P("95046P", "perm. funz. pubb. Pres. Cons. provin. 6 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_95046S("95046S", "perm. funz. pubb. Sindaci di prov. 6 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_95047("95047", "perm. funz. pubb. giunte provinc. 7 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  A_95047E("95047E", "perm. funz. pubb. O. E. provinciali  7 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  A_95047P("95047P", "perm. funz. pubb. Pres. Cons. provin. 7 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  A_95047S("95047S", "perm. funz. pubb. Sindaci di prov. 7 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  A_95051("95051", "perm. funz. pubb. comun.Giunt. Comm. 1h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_95051E("95051E", "perm. funz. pubb. O. E. com. e Un. com. 1 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_95051P("95051P", "perm. funz. pubb. Pres. Cons. comun.  1 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_95056E("95056E", "perm. funz. pubb. O. E. com. e Un. com. 6 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_95056P("95056P", "perm. funz. pubb. Pres. Cons. comun. 6 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_95057("95057", "perm. funz. pubb. comun. Giunt. Comm. 7 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  A_95064P("95064P", "perm. funz. pubb. Pres. comun. monta. 4 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_95065("95065", "perm. funz. pubb. Giunte comun. mon. 5 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_95065E("95065E", "perm. funz. pubb. O. E.c omunit  mon. 5 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_95065P("95065P", "perm. funz. pubb. Pres. comun. monta. 5 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_95066("95066", "perm. funz. pubb. Giunte comun. mon. 6 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_95066E("95066E", "perm. funz. pubb. O. E. comunit mon. 6 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_95066P("95066P", "perm. funz. pubb. Pres. comun. monta. 6 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_95067("95067", "perm. funz. pubb.Giunte comun. mon. 7 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  A_95067E("95067E", "perm. funz. pubb. O. E. comunit  mon. 7 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  A_95067P("95067P", "perm. funz. pubb. Pres. comun. monta. 7 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  A_95064E("95064E", "perm. funz. pubb. O. E. comunit mon .4 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_95064("95064", "perm. funz. pubb. Giunte comun. mon. 4 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_95063P("95063P", "perm. funz. pubb. Pres. comun. monta. 3 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_95057E("95057E", "perm. funz. pubb. O. E. com. e Un.com. 7 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  A_95057P("95057P", "perm.f unz. pubb. Pres. Cons. comun. 7 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  A_95061("95061", "perm. funz. pubb. Giunte comun. mon. 1 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_95061E("95061E", "perm. funz. pubb. O. E. comunita mon. 1 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_95061P("95061P", "perm. funz. pubb. Pres. comun. monta. 1 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_95062("95062", "perm. funz. pubb.Giunte comun mon. 2 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  A_95062E("95062E", "perm. funz. pubb. O. E. comunit mon. 2 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  A_95062P("95062P", "perm. funz. pubb. Pres. comun. monta. 2 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  A_95063("95063", "perm. funz. pubb. Giunte comun. mon. 3 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_95063E("95063E", "perm. funz. pubb. O. E. comunit  mon. 3 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_95101("95101", "perm. funz .pubb. O. E. municipali 1 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_95045S("95045S", "perm. funz. pubb. Sindaci di prov. 5 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_95012E("95012E", "perm. funz. pubb. O. E. citta metrop. 2 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  A_95017("95017", "perm. funz. pubb.Giunt. citta metr. 7 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  A_95017E("95017E", "perm. funz. pubb. O. E. citta metrop. 7 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  A_95017S("95017S", "perm. funz. pubb. Sindaci metropol. 7 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  A_9502("9502", "perm. funz. pubb. Cons. circoscrizion.",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_95021("95021", "perm. funz. pubb. O. E. Cons. Comm. cir. 1h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_95021P("95021P", "perm. funz. pubb. Presidenti circo. 1 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_95022("95022", "perm. funz. pubb. O. E. Cons. Comm. cir. 2h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  A_95022P("95022P", "perm. funz. pubb. Presidenti circo. 2 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  A_95023("95023", "perm. funz. pubb. O. E. Cons. Comm. cir. 3h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_95023P("95023P", "perm. funz. pubb. Presidenti circo. 3 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_95016S("95016S", "perm. funz. pubb. Sindaci metropol. 6 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_95016E("95016E", "perm. funz. pubb. O. E. citta metrop. 6 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_95016("95016", "perm. funz. pubb.Giunt. citta metr. 6 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_95012S("95012S", "perm. funz. pubb.Sindaci metropol. 2 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  A_95013("95013", "perm. funz. pubb. Giunt.citta metr. 3 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_95013E("95013E", "perm. funz. pubb. O. E. citta metrop. 3 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_95013S("95013S", "perm. funz. pubb.Sindaci metropol. 3 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_95014("95014", "perm. funz. pubb.Giunt.citta metr. 4 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_95014E("95014E", "perm. funz. pubb. O. E. citta metrop. 4 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_95014S("95014S", "perm. funz. pubb. Sindaci metropol. 4 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_95015("95015", "perm. funz. pubb. Giunt. citta metr. 5 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_95015E("95015E", "perm. funz. pubb. O. E. citta metrop. 5 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_95015S("95015S", "perm. funz. pubb. Sindaci metropol. 5 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_95024("95024", "perm. funz. pubb. O. E. Cons. Comm. cir. 4h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_95024P("95024P", "perm. funz. pubb.Presidenti circo. 4 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_95025("95025", "perm. funz. pubb. O. E. Cons. Comm. cir. 5h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_95043("95043", "perm. funz. pubb. giunte provinc. 3 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_95001("95001", "perm. funz. pubb. non retribuito 1 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_95043E("95043E", "perm. funz. pubb. O. E. provinciali 3 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_95002("95002", "perm. funz. pubb. non retribuito 2 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  A_95043P("95043P", "perm. funz. pubb. Pres. Cons. provin. 3 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_95003("95003", "perm. funz. pubb. non retribuito 3 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_95043S("95043S", "perm. funz. pubb. Sindaci di prov. 3 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_95004("95004", "perm. funz. pubb. non retribuito 4 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_95044("95044", "perm. funz. pubb. giunte provinc. 4 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_95005("95005", "perm. funz. pubb. non retribuito 5 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_95044E("95044E", "perm.f unz. pubb. O. E. provinciali 4 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_95006("95006", "perm. funz. pubb. non retribuito 6 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_95044P("95044P", "perm. funz. pubb. Pres. Cons. provin. 4 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_95007("95007", "perm. funz. pubb. non retribuito 7 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  A_95044S("95044S", "perm. funz. pubb. Sindaci di prov.  4 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_9501("9501", "perm. funz. pubb. Consig. cittametrop.",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_95045("95045", "perm. funz. pubb. giunte provinc. 4 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_95011("95011", "perm. funz. pubb. Giunt. citta  metr. 1 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_95045E("95045E", "perm. funz. pubb. O. E. provinciali 5 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_95011E("95011E", "perm. funz. pubb. O. E. citta metrop. 1 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_95042S("95042S", "perm. funz. pubb. Sindaci di prov. 2 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  A_95042P("95042P", "perm. funz. pubb. Pres. Cons. provin. 2 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),

  A_95042E("95042E", "perm. funz. pubb. O. E. provinciali 2 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  A_95025P("95025P", "perm. funz. pubb. Presidenti circo. 5 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_95026("95026", "perm. funz. pubb. O. E. Cons. Comm. cir. 6h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_95026P("95026P", "perm. funz. pubb. Presidenti circo. 6 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_95027("95027", "perm. funz. pubb. O. E. Cons. Comm. cir. 7h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  A_95027P("95027P", "perm. funz. pubb. Presidenti circo. 7 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  A_95041("95041", "perm. funz. pubb. giunte provinc. 1 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_95041E("95041E", "perm. funz. pubb. O. E. provinciali  1 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_95041P("95041P", "perm. funz. pubb. Pres.Cons. provin. 1 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_95041S("95041S", "perm. funz. pubb. Sindaci di prov. 1 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_95042("95042", "perm. funz. pubb. giunte provinc. 2 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  A_95045P("95045P", "perm. funz. pubb. Pres. Cons. provin. 5 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_95011S("95011S", "perm. funz. pubb.Sindaci metropol. 1 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_9599("9599", "permesso funzione pubbliche varie",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_9509("9509", "permesso funzione pubblica ASL",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_9508("9508", "permesso funzione pubblica enti regionali",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_9503("9503", "permesso funzione pubblica cons. e giunte reg.",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_9504("9504", "permesso funzione pubblica cons. e giunte prov.",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_9505("9505", "permesso funzione pubblica cons. e giunte comunali",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_9506("9506", "permesso funzione pubblica comunità montane",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_9507("9507", "permesso funzione pubblica consorzi comunali",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_9591("9591", "riposo compens. funz. pubblica",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_9599B("9599B", "Permesso per citazione a testimoniare o espl. funzioni giudice popolare",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_95102("95102", "perm. funz. pubb. O. E. municipali  2 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  A_95115("95115", "perm. funz. pubb. O. E. Co. Un. Com.En. L 5h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_95115E("95115E", "perm. funz. pubb. O. E. Cons. enti loc. 5h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_95116("95116", "perm. funz. pubb. O. E. Co. Un. Com. En. L 6h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_95116E("95116E", "perm. funz. pubb. O. E. Cons. enti loc. 6h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_95117("95117", "perm. funz. pubb. O. E. Co. Un. Com. En. L 7h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  A_95117E("95117E", "perm. funz. pubb. O. E. Cons. enti loc. 7h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  A_95E("95E", "perm. funz. pubb. Parlamento Europeo",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_95N("95N", "perm. funz. pubb. Parlamento Nazionale",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_95114E("95114E", "perm. funz. pubb. O. E.Cons. enti loc. 4h",
      false, ImmutableSet.of(JustifiedTypeName.all_day), 0, false, false,
      0, null, null, null),
  A_95114("95114", "perm. funz. pubb. O. E. Co. Un. Com En. L 4h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_95113E("95113E", "perm. funz. pubb. O. E. Cons. enti loc. 2h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_95103("95103", "perm. funz. pubb. O. E. municipali 3 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_95104("95104", "perm. funz. pubb. O. E. municipali 4",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 240, false, false,
      0, null, null, null),
  A_95105("95105", "perm. funz. pubb. O. E. municipali 5 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 300, false, false,
      0, null, null, null),
  A_95106("95106", "perm. funz. pubb. O. E. municipali 6 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 360, false, false,
      0, null, null, null),
  A_95107("95107", "perm. funz. pubb. O. E. municipali 7 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 420, false, false,
      0, null, null, null),
  A_95111("95111", "perm. funz. pubb. O. E. Co. Un. Com. En. L 1h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_95111E("95111E", "perm. funz. pubb. O. E. Cons. enti loc. 1h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 60, false, false,
      0, null, null, null),
  A_95112("95112", "perm. funz. pubb. O. E. Co. Un. Com. En. L 2h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  A_95112E("95112E", "perm. funz. pubb. O. E. Cons. enti loc. 2h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null),
  A_95113("95113", "perm. funz. pubb. O. E. Co .Un. Com. En. L 3h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 180, false, false,
      0, null, null, null),
  A_95012("95012", "perm. funz. pubb.Giunt. citta metr. 2 h",
      false, ImmutableSet.of(JustifiedTypeName.absence_type_minutes), 120, false, false,
      0, null, null, null);


  public String certificationCode;
  public String description;
  public boolean internalUse;

  public Set<JustifiedTypeName> justifiedTypeNamesPermitted;
  public Integer justifiedTime;                              

  public boolean consideredWeekEnd;

  public boolean timeForMealTicket;

  public Integer replacingTime;
  public JustifiedTypeName replacingType;                     //nullable

  public LocalDate validFrom;                                 //nullable
  public LocalDate validTo;                                   //nullable

  private DefaultAbsenceType(String certificationCode, String description, boolean internalUse, 
      Set<JustifiedTypeName> justifiedTypeNamesPermitted, Integer justifiedTime, 
      boolean consideredWeekEnd, boolean timeForMealTicket, 
      Integer replacingTime, JustifiedTypeName replacingType,
      LocalDate validFrom, LocalDate validTo) {
    this.certificationCode = certificationCode;
    this.description = description;
    this.internalUse = internalUse;
    this.justifiedTypeNamesPermitted = justifiedTypeNamesPermitted;
    this.justifiedTime = justifiedTime;
    this.consideredWeekEnd = consideredWeekEnd;
    this.timeForMealTicket = timeForMealTicket;
    this.replacingTime = replacingTime;
    this.replacingType = replacingType;
    this.validFrom = validFrom;
    this.validTo = validTo;

  }

  /**
   * Ricerca i codici assenza modellati e non presenti fra quelle passate in arg (db).
   * @return list
   */
  public static List<DefaultAbsenceType> missing(List<AbsenceType> allAbsenceTypes) {
    List<DefaultAbsenceType> missing = Lists.newArrayList();
    for (DefaultAbsenceType defaultTypes : DefaultAbsenceType.values()) {
      boolean found = false;
      for (AbsenceType type : allAbsenceTypes) {
        if (defaultTypes.getCode().equals(type.code)) {
          found = true;
          break;
        }
      }
      if (!found) {
        missing.add(defaultTypes);
      }
    }
    return missing;
  }

  public String getCode() {
    return this.name().substring(2);
  }
  
  /**
   * L'enumerato corrispettivo del absenceType (se esiste...) 
   * @return optional dell'enumerato
   */
  public static Optional<DefaultAbsenceType> byCode(AbsenceType absenceType) {
    for (DefaultAbsenceType defaultAbsenceType : DefaultAbsenceType.values()) {
      if (absenceType.code.equals(defaultAbsenceType.getCode())) {
        return Optional.of(defaultAbsenceType);
      }
    }
    return Optional.absent();
  }

}